# dsh-mobile-remote installer: install into web profile + write config
# Usage: powershell -ExecutionPolicy Bypass -File install.ps1
#        powershell -ExecutionPolicy Bypass -File install.ps1 -Password yourpass
param([string]$Password = '')

$ErrorActionPreference = 'Stop'
$here = $PSScriptRoot
$profile = Join-Path $env:USERPROFILE '.dsh\profiles\web'
$patchFile = Join-Path $profile 'cordis.patch.yml'

if (-not (Test-Path $profile)) {
  Write-Host "ERROR: web profile not found: $profile" -ForegroundColor Red
  exit 1
}
if (-not $Password) {
  $Password = Read-Host 'Phone access password (Enter for dsh-6982)'
}
if (-not $Password) { $Password = 'dsh-6982' }

Write-Host '==> 1/3 installing plugin package into web profile ...' -ForegroundColor Cyan
if (Test-Path (Join-Path $here 'node_modules')) { Remove-Item (Join-Path $here 'node_modules') -Recurse -Force }
$targetPkg = Join-Path $profile 'node_modules\dsh-mobile-remote'

# Copy package folder into profile node_modules (cordis loader resolves by
# package name from that dir; same effect as `dsh plugin add`, no pnpm needed)
if (Test-Path $targetPkg) { Remove-Item $targetPkg -Recurse -Force }
New-Item -ItemType Directory -Path $targetPkg -Force | Out-Null
Copy-Item "$here\lib" (Join-Path $targetPkg 'lib') -Recurse -Force
Copy-Item "$here\web" (Join-Path $targetPkg 'web') -Recurse -Force
Copy-Item "$here\package.json" (Join-Path $targetPkg 'package.json') -Force
$installed = $true

if (-not $installed) {
  Write-Host 'ERROR: install failed. Manually copy this folder to %USERPROFILE%\.dsh\profiles\web\node_modules\dsh-mobile-remote' -ForegroundColor Red
  exit 1
}

Write-Host '==> 2/3 backing up and writing cordis.patch.yml ...' -ForegroundColor Cyan
if (Test-Path $patchFile) { Copy-Item $patchFile "$patchFile.bak" -Force }
$patch = @"
# dsh-mobile-remote config (generated by install.ps1; edit password and restart dsh web)
# Security model:
#   - webserver binds 0.0.0.0 so the phone can reach this port via Pgy/Tailscale
#   - connection.trustedHosts emptied -> /api trusts loopback only;
#     remote access works ONLY through the password-protected /m/* mobile UI
- id: webserver
  config:
    host: !!js ctx.webStartup.host ?? '0.0.0.0'
    port: !!js ctx.webStartup.port ?? 3080
- id: connection
  config:
    trustedHosts: []
- insert:
    - id: mobile-remote
      name: 'dsh-mobile-remote'
      config:
        password: '$Password'
"@
Set-Content -Path $patchFile -Value $patch -Encoding UTF8

Write-Host '==> 3/3 done!' -ForegroundColor Green
Write-Host ''
Write-Host 'NEXT: restart dsh web to activate (IMPORTANT)' -ForegroundColor Yellow
Write-Host '  1) Stop current dsh web (Ctrl+C or close its window) - this chat pauses briefly and resumes automatically'
Write-Host '  2) Start dsh web again the same way as before (e.g. dsh web)'
Write-Host "  3) Phone: open http://<PC-Pgy-IP>:3080/m/ with password: $Password"
Write-Host ''
Write-Host 'Rollback:' -ForegroundColor Cyan
Write-Host '  Config: copy cordis.patch.yml.bak back to cordis.patch.yml'
Write-Host '  Uninstall: remove %USERPROFILE%\.dsh\profiles\web\node_modules\dsh-mobile-remote'
